language: php
dist: precise
php:
  - 5.6

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update && composer install --no-interaction
  - cd tests


script: phpunit --stderr
after_script:
  - pwd
#  - cd ../
##  - git init
#  - git config --global user.name "yakeing"
#  - git config --global user.email "yakeing@gmail.com"
#  - git tag v1.3
#  - git show v1.3
#  - git push --force --tags --quiet "https://${TOKEN}@github.com/yakeing/php_session.git" master:master
