language: php
dist: precise
php:
  - 5.6

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update && composer install --no-interaction
  - cd tests

script: phpunit --stderr
after_script:
  - git tag -a v1.3
  - git push origin --tags